# Generated by Django 5.2.1 on 2026-09-30 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_uploadedfile_uploaded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('leave_approved', 'Leave Approved'), ('leave_rejected', 'Leave Rejected'), ('attendance_approved', 'Attendance Approved'), ('attendance_rejected', 'Attendance Rejected'), ('leave_submitted', 'Leave Request Submitted'), ('attendance_pending', 'Attendance Awaiting Approval'), ('profile_updated', 'Profile Updated'), ('admin_prompt', 'Administrator Message'), ('employee_activity', 'Employee Activity'), ('system_alert', 'System Alert')], max_length=30),
        ),
    ]
